version: '3.8'

services:
  rust_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_api_container
    ports:
      - "8080:8080"
    environment: {}
    restart: unless-stopped
